sudo luarocks install argcheck
sudo luarocks install csvigo
sudo luarocks install cudnn
sudo luarocks install cunn
sudo luarocks install cunnx
sudo luarocks install cutorch
sudo luarocks install cwrap
sudo luarocks install dataload
sudo luarocks install dataprovider
sudo luarocks install dok
sudo luarocks install dpnn
sudo luarocks install eladtools
sudo luarocks install env
sudo luarocks install gnuplot
sudo luarocks install graph
sudo luarocks install graphicsmagick
sudo luarocks install image
sudo luarocks install itorch
sudo luarocks install lbase64
sudo luarocks install lua-cjson
sudo luarocks install lua-csnappy
sudo luarocks install luacrypto
sudo luarocks install luaffi
sudo luarocks install luafilesystem
sudo luarocks install lzmq
sudo luarocks install md5
sudo luarocks install mnist
sudo luarocks install moses
sudo luarocks install nn
sudo luarocks install nngraph
sudo luarocks install nninit
sudo luarocks install nnx
sudo luarocks install optim
sudo luarocks install paths
sudo luarocks install penlight
sudo luarocks install qtlua
sudo luarocks install qttorch
sudo luarocks install recurrent
sudo luarocks install regress
sudo luarocks install rnn
sudo luarocks install sundown
sudo luarocks install sys
sudo luarocks install threads
sudo luarocks install torch
sudo luarocks install torchx
sudo luarocks install trepl
sudo luarocks install uuid
sudo luarocks install xlua
