luarocks install  argcheck
luarocks install  csvigo
luarocks install  cudnn
luarocks install  cunn
luarocks install  cunnx
luarocks install  cutorch
luarocks install  cwrap
luarocks install  dataload
luarocks install  dataprovider
luarocks install  dok
luarocks install  dpnn
luarocks install  eladtools
luarocks install  env
luarocks install  gnuplot
luarocks install  graph
luarocks install  graphicsmagick
luarocks install  image
luarocks install  itorch
luarocks install  lbase64
luarocks install  lua-cjson
luarocks install  lua-csnappy
luarocks install  luacrypto
luarocks install  luaffi
luarocks install  luafilesystem
luarocks install  lzmq
luarocks install  md5
luarocks install  mnist
luarocks install  moses
luarocks install  nn
luarocks install  nngraph
luarocks install  nninit
luarocks install  nnx
luarocks install  optim
luarocks install  paths
luarocks install  penlight
luarocks install  qtlua
luarocks install  qttorch
luarocks install  recurrent
luarocks install  regress
luarocks install  rnn
luarocks install  sundown
luarocks install  sys
luarocks install  threads
luarocks install  torch
luarocks install  torchx
luarocks install  trepl
luarocks install  uuid
luarocks install  xlua
