luarocks install --local argcheck
luarocks install --local csvigo
luarocks install --local cudnn
luarocks install --local cunn
luarocks install --local cunnx
luarocks install --local cutorch
luarocks install --local cwrap
luarocks install --local dataload
luarocks install --local dataprovider
luarocks install --local dok
luarocks install --local dpnn
luarocks install --local eladtools
luarocks install --local env
luarocks install --local gnuplot
luarocks install --local graph
luarocks install --local graphicsmagick
luarocks install --local image
luarocks install --local itorch
luarocks install --local lbase64
luarocks install --local lua-cjson
luarocks install --local lua-csnappy
luarocks install --local luacrypto
luarocks install --local luaffi
luarocks install --local luafilesystem
luarocks install --local lzmq
luarocks install --local md5
luarocks install --local mnist
luarocks install --local moses
luarocks install --local nn
luarocks install --local nngraph
luarocks install --local nninit
luarocks install --local nnx
luarocks install --local optim
luarocks install --local paths
luarocks install --local penlight
luarocks install --local qtlua
luarocks install --local qttorch
luarocks install --local recurrent
luarocks install --local regress
luarocks install --local rnn
luarocks install --local sundown
luarocks install --local sys
luarocks install --local threads
luarocks install --local torch
luarocks install --local torchx
luarocks install --local trepl
luarocks install --local uuid
luarocks install --local xlua
