luarocks install --local torch
luarocks install --local cutorch
luarocks install --local nn
luarocks install --local cunn
luarocks install --local cudnn
luarocks install --local nninit
luarocks install --local recurrent
luarocks install --local torchx
luarocks install --local dpnn
luarocks install --local cunnx
luarocks install --local rnn
